/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2008
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/


/*******************************************************************************
 *
 * Filename:
 * ---------
 *   gpio_jni.c
 *
 * Project:
 * --------
 *   Android
 *
 * Description:
 * ------------
 *    c file of gpio jni function
 *
 * Author:
 * -------
 *   MTK80905

 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include "gpio_jni.h"
#include "string.h"
#include "Meta_GPIO_Para.h"
#include "funk.h"


/*
 * Class:     com_mediatek_engineermode_gpio
 * Method:    GPIO_Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_engineermode_io_EmGpio_gpioInit
  (JNIEnv * env, jobject obj)
  {
  	return Meta_GPIO_Init()? JNI_TRUE: JNI_FALSE;
  	
  }

/*
 * Class:     com_mediatek_engineermode_gpio
 * Method:    GPIO_UnInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_engineermode_io_EmGpio_gpioUnInit
  (JNIEnv * env, jobject obj)
  {  	
  	return Meta_GPIO_Deinit()? JNI_TRUE: JNI_FALSE;
  }

/*
 * Class:     com_mediatek_engineermode_gpio
 * Method:    Get_gpio_max_number
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_engineermode_io_EmGpio_getGpioMaxNumber
  (JNIEnv *env, jobject obj)
  {
  	return (jint)HW_GPIO_MAX;
  }

/*
 * Class:     com_mediatek_engineermode_gpio
 * Method:    Set_gpio_input
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_engineermode_io_EmGpio_setGpioInput
  (JNIEnv *env, jobject obj, jint n)
  {
  	GPIO_REQ req;
  	memset(&req, 0, sizeof(GPIO_REQ));  	
  	req.pin = (int)n;
  	req.op = SET_DIR_IN;
  	
  	GPIO_CNF r = Meta_GPIO_OP(req, 0, 0);
  	return r.status == META_SUCCESS ? JNI_TRUE : JNI_FALSE;
  }

/*
 * Class:     com_mediatek_engineermode_gpio
 * Method:    Set_gpio_output
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_engineermode_io_EmGpio_setGpioOutput
  (JNIEnv * env, jobject obj, jint n)
  {
  	GPIO_REQ req;
  	memset(&req, 0, sizeof(GPIO_REQ));  	
  	req.pin = (int)n;
  	req.op = SET_DIR_OUT;
  	
  	GPIO_CNF r = Meta_GPIO_OP(req, 0, 0);
  	return r.status == META_SUCCESS ? JNI_TRUE : JNI_FALSE;
  }

/*
 * Class:     com_mediatek_engineermode_gpio
 * Method:    Set_gpio_data_high
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_engineermode_io_EmGpio_setGpioDataHigh
  (JNIEnv * env, jobject obj, jint n)
  {
  	GPIO_REQ req;
  	memset(&req, 0, sizeof(GPIO_REQ));  	
  	req.pin = (int)n;
  	req.op = SET_DATA_HIGH;
  	
  	GPIO_CNF r = Meta_GPIO_OP(req, 0, 0);
  	return r.status == META_SUCCESS ? JNI_TRUE : JNI_FALSE;
  }

/*
 * Class:     com_mediatek_engineermode_gpio
 * Method:    Set_gpio_data_low
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_engineermode_io_EmGpio_setGpioDataLow
  (JNIEnv * env, jobject obj, jint n)
  {
  	GPIO_REQ req;
  	memset(&req, 0, sizeof(GPIO_REQ));  	
  	req.pin = (int)n;
  	req.op = SET_DATA_LOW;
  	
  	GPIO_CNF r = Meta_GPIO_OP(req, 0, 0);
  	return r.status == META_SUCCESS ? JNI_TRUE : JNI_FALSE;
  }
   

