
TARGET_ARCH_VARIANT = armv7-a-neon



MTK_FIRST_MD = 1
MTK_FOTA_ENTRY = no
MTK_FLIGHT_MODE_POWER_OFF_MD = yes


MTK_SCOMO_ENTRY = no

MTK_OGM_PLAYBACK_SUPPORT = no

MTK_MTKPS_PLAYBACK_SUPPORT = no
MTK_MMPROFILE_SUPPORT=yes

MTK_DP_FRAMEWORK = yes
MTK_ION_SUPPORT = yes

MTK_ENABLE_MD1 = yes
MTK_ENABLE_MD2 = no


CUSTOM_KERNEL_SSW=ssw_single

MTK_SWIP_VORBIS=yes

MULTI_CH_PLAYBACK_SUPPORT=no


MTK_PRODUCT_INFO_SUPPORT=yes


DMNR_TUNNING_AT_MODEMSIDE=no

MTK_USES_VR_DYNAMIC_QUALITY_MECHANISM=yes
MTK_PQ_SUPPORT=PQ_HW_VER_2
MTK_FM_RX_AUDIO=FM_DIGITAL_INPUT

MTK_BWC_SUPPORT = yes




MTK_LCEEFT_SUPPORT = yes

MTK_WFD_SUPPORT=yes

GEMINI=yes
MTK_GEMINI_3G_SWITCH=yes
MTK_GEMINI_ENHANCEMENT=yes
MTK_SHARE_MODEM_CURRENT=2
MTK_SHARE_MODEM_SUPPORT=2

MTK_WLAN_SUPPORT = yes
MTK_WLAN_CHIP = CONSYS_MT6572

# the compiler option for HWUI using OpenGLES2.0

# common part
MTK_COMBO_SUPPORT=yes
CUSTOM_HAL_COMBO=mt6572_82
CUSTOM_HAL_ANT=mt6582_ant_m1
MTK_COMBO_CHIP=CONSYS_6572

# Bluetooth chip type
MTK_BT_CHIP= MTK_CONSYS_MT6572

MTK_SEC_SECRO_AC_SUPPORT = yes

MTK_MD_SHUT_DOWN_NT = yes


# To identify which GPS chip be used on current platform.
MTK_GPS_CHIP=MTK_GPS_MT6572

# a utility application that is relative to engineer mode, provide support on testing of GPS function.

# Be used to switch GPS feature on the platform. Set "yes" to turn on and set "no"(with MTK_AGPS_APP=no at the same time) to turn off.
MTK_GPS_SUPPORT=yes

MTK_USE_RESERVED_EXT_MEM = no


# Enable Scatter file as YAML format
MTK_YAML_SCATTER_FILE_SUPPORT=yes

MTK_VIDEO_FAVORITES_WIDGET_APP = no

MTK_WB_SPEECH_SUPPORT = yes


MTK_UART_USB_SWITCH = yes

MTK_AUDENH_SUPPORT = yes 


MTK_DATAUSAGE_SUPPORT = no


MTK_DATAUSAGELOCKSCREENCLIENT_SUPPORT = no


MTK_SUPPORT_MJPEG = yes


MTK_MAV_PLAYBACK_SUPPORT = no

# To enable HWC
MTK_HWC_SUPPORT = yes
MTK_HWC_VERSION = 1.2

MTK_SINA_WEIBO_SUPPORT = no

MTK_FENCE_SUPPORT = yes

MTK_NAND_PAGE_SIZE=4K


MTK_GEMINI_SMART_3G_SWITCH = 1


MTK_BT_PROFILE_PRXM=no
MTK_BT_PROFILE_PRXR=no

MTK_MEM_PRESERVED_MODE_ENABLE = no
LINUX_KERNEL_VERSION = kernel-3.4

MTK_MOBILE_MANAGEMENT = yes 

MTK_PERMISSION_CONTROL = yes 

MTK_BT_40_SUPPORT = yes
LEGACY_DFO_GEN=yes
MD1_SIZE = ref:chkMDSize.pl md1
MD2_SIZE = ref:chkMDSize.pl md2
MTK_VIDEO_1080P = yes
MTK_PASSPOINT_R1_SUPPORT = no
