/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6582. Copyright MediaTek Inc. (C) 2013.
 * Tue Feb 25 19:51:43 2014
 * Do Not Modify the File.
 */






/**********Output default name********************/

#define PMIC_APP_Camera_A         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_Camera_A2         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_Camera_D         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_Camera_D2         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_G_sensor         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_M_3G_PA         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_M_sensor         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_Cap_touch         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_Cyroscope         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_WiFi2V8         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_WiFi1V8         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_Bluetooth         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_FM_Radio         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_BFC         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_OFN         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_Vibrator         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_Memory_Card         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_SIM2         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_mATV         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_CMMB         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_eMMC         MT6323_POWER_LDO_DEFAULT
#define PMIC_APP_Others         MT6323_POWER_LDO_DEFAULT


