#ifndef FTM_CUST_LED_H
#define FTM_CUST_LED_H

#define CUST_LED_HAVE_RED
//LINE<JIRA_ID><DATE20140314><BUG_INFO>zenghaihui
#define CUST_LED_HAVE_GREEN
#define CUST_LED_HAVE_BUTTON_BACKLIGHT

#endif /* FTM_CUST_LED_H */
