/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to MediaTek Inc. and/or its licensors. Without
 * the prior written permission of MediaTek inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of MediaTek Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 * 
 * MediaTek Inc. (C) 2010. All rights reserved.
 * 
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
 * MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek
 * Software") have been modified by MediaTek Inc. All revisions are subject to
 * any receiver's applicable license agreements with MediaTek Inc.
 */

#ifndef PLL_H
#define PLL_H

#define AP_PLL_CON0         (APMIXED_BASE+0x000)
#define AP_PLL_CON1         (APMIXED_BASE+0x004)
#define AP_PLL_CON2         (APMIXED_BASE+0x008)
#define AP_PLL_CON3         (APMIXED_BASE+0x00C)
#define AP_PLL_CON4         (APMIXED_BASE+0x010)

#define PLL_HP_CON0         (APMIXED_BASE+0x014)
#define PLL_HP_CON1         (APMIXED_BASE+0x018)

#define CLKSQ_STB_CON0      (APMIXED_BASE+0x01C)

#define PLL_PWR_CON0        (APMIXED_BASE+0x020)
#define PLL_PWR_CON1        (APMIXED_BASE+0x024)
#define PLL_PWR_CON2        (APMIXED_BASE+0x028)
#define PLL_PWR_CON3        (APMIXED_BASE+0x02C)

#define PLL_ISO_CON0        (APMIXED_BASE+0x030)
#define PLL_ISO_CON1        (APMIXED_BASE+0x034)
#define PLL_ISO_CON2        (APMIXED_BASE+0x038)
#define PLL_ISO_CON3        (APMIXED_BASE+0x03C)

#define PLL_EN_CON0         (APMIXED_BASE+0x040)
#define PLL_EN_CON1         (APMIXED_BASE+0x044)

#define PLL_STB_CON0        (APMIXED_BASE+0x048)
#define PLL_STB_CON1        (APMIXED_BASE+0x04C)
#define PLL_STB_CON2        (APMIXED_BASE+0x050)

#define DIV_STB_CON0        (APMIXED_BASE+0x054)

#define PLL_CHG_CON0        (APMIXED_BASE+0x058)
#define PLL_CHG_CON1        (APMIXED_BASE+0x05C)

#define PLL_TEST_CON0       (APMIXED_BASE+0x060)
#define PLL_TEST_CON1       (APMIXED_BASE+0x064)

#define ARMPLL_CON0         (APMIXED_BASE+0x100)
#define ARMPLL_CON1         (APMIXED_BASE+0x104)
#define ARMPLL_CON2         (APMIXED_BASE+0x108)
#define ARMPLL_CON3         (APMIXED_BASE+0x10C)
#define ARMPLL_CON3         (APMIXED_BASE+0x10C)
#define ARMPLL_PWR_CON0     (APMIXED_BASE+0x110)

#define MAINPLL_CON0        (APMIXED_BASE+0x120)
#define MAINPLL_CON1        (APMIXED_BASE+0x124)
#define MAINPLL_CON2        (APMIXED_BASE+0x128)
#define MAINPLL_CON3        (APMIXED_BASE+0x12C)
#define MAINPLL_PWR_CON0    (APMIXED_BASE+0x130)

#define UNIVPLL_CON0        (APMIXED_BASE+0x140)
#define UNIVPLL_CON1        (APMIXED_BASE+0x144)
#define UNIVPLL_CON2        (APMIXED_BASE+0x148)
#define UNIVPLL_CON3        (APMIXED_BASE+0x14C)
#define UNIVPLL_PWR_CON0    (APMIXED_BASE+0x150)

#define AP_ABIST_MON_CON0   (APMIXED_BASE+0xE00)
#define AP_ABIST_MON_CON1   (APMIXED_BASE+0xE04)
#define AP_ABIST_MON_CON2   (APMIXED_BASE+0xE08)
#define AP_ABIST_MON_CON3   (APMIXED_BASE+0xE0C)

#define CLK_SEL_0           (TOP_CLKCTRL_BASE+0x000)
#define CLK_SEL_2           (TOP_CLKCTRL_BASE+0x008)
#define CLK_SEL_3           (TOP_CLKCTRL_BASE+0x00C)
#define CLK_SEL_4           (TOP_CLKCTRL_BASE+0x010)
#define CLK_SWCG_0          (TOP_CLKCTRL_BASE+0x020)
#define CLK_SWCG_1          (TOP_CLKCTRL_BASE+0x024)
#define CLK_SWCG_2          (TOP_CLKCTRL_BASE+0x028)
#define CLK_SWCG_3          (TOP_CLKCTRL_BASE+0x02C)
#define CLK_SWCG_4          (TOP_CLKCTRL_BASE+0x030)
#define CLK_SWCG_5          (TOP_CLKCTRL_BASE+0x034)
#define CLK_SWCG_5          (TOP_CLKCTRL_BASE+0x038)
#define CLK_SETCG_0         (TOP_CLKCTRL_BASE+0x050)
#define CLK_SETCG_1         (TOP_CLKCTRL_BASE+0x054)
#define CLK_SETCG_2         (TOP_CLKCTRL_BASE+0x058)
#define CLK_SETCG_3         (TOP_CLKCTRL_BASE+0x05C)
#define CLK_SETCG_4         (TOP_CLKCTRL_BASE+0x060)
#define CLK_SETCG_5         (TOP_CLKCTRL_BASE+0x064)
#define CLK_SETCG_6         (TOP_CLKCTRL_BASE+0x068)
#define CLK_CLRCG_0         (TOP_CLKCTRL_BASE+0x080)
#define CLK_CLRCG_1         (TOP_CLKCTRL_BASE+0x084)

#define ACLKEN_DIV          (APMCUSYS_CONFIG_BASE+0x060)
#define PCLKEN_DIV          (APMCUSYS_CONFIG_BASE+0x064)

#define INFRA_TOPCKGEN_CKMUXSEL (CONFIG_BASE+0x000)

typedef enum {
    PLL_UART0,
    PLL_UART1,
    NUM_OF_UART
} pll_uart_id;

#endif
