/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */


/*******************************************************************************
 *
 * Filename:
 * ---------
 *  
 *
 * Project:
 * --------
 *   Android
 *
 * Description:
 * ------------
 *    c file of feature support jni function
 *
 * Author:
 * -------
 *   MTK80905

 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


enum{
	MTK_FM_SUPPORT_STUB = 0,
    MTK_FM_TX_SUPPORT_STUB ,
    MTK_RADIO_SUPPORT_STUB ,
    MTK_AGPS_APP_STUB,
    MTK_GPS_SUPPORT_STUB ,
    HAVE_MATV_FEATURE_STUB,
    MTK_BT_SUPPORT_STUB ,
    MTK_WLAN_SUPPORT_STUB ,
    MTK_TTY_SUPPORT_STUB ,
    MTK_NFC_SUPPORT_STUB ,
    FEATURE_MAX_IDX 
};

static int support_items[] = {
#ifdef MTK_FM_SUPPORT
    1,   
#else
		0, 		
#endif
#ifdef MTK_FM_TX_SUPPORT
    1,
#else
		0,
#endif
#ifdef MTK_RADIO_SUPPORT
    1,
#else
		0,
#endif
#ifdef MTK_AGPS_APP
    1,
#else
		0,
#endif
#ifdef MTK_GPS_SUPPORT
    1,
#else
		0,
#endif
#ifdef HAVE_MATV_FEATURE
    1,
#else
		0,
#endif
#ifdef MTK_BT_SUPPORT
    1,
#else
		0,
#endif
#ifdef MTK_WLAN_SUPPORT
    1,
#else
		0,
#endif
#ifdef MTK_TTY_SUPPORT
    1,
#else
		0,
#endif
#ifdef MTK_NFC_SUPPORT
    1,
#else
		0,
#endif

    999
};

JNIEXPORT jboolean JNICALL Java_com_mediatek_engineermode_ChipSupport_isFeatureSupported
  (JNIEnv * env, jobject obj, jint feature_id)
  {
  	if(feature_id >= FEATURE_MAX_IDX || feature_id < 0)
  		return JNI_FALSE;
  	else
		return support_items[feature_id] == 1 ? JNI_TRUE:JNI_FALSE;  	
  }



